import type { Metadata } from "next";
import "./globals.css";
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarTrigger,
} from "@/components/ui/menubar";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { useForm } from "react-hook-form";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="flex items-center px-4 py-2">
          <div className="ml-auto">
            <Button variant="outline">
              <Link href="login">Login</Link>
            </Button>
          </div>
        </div>
        <Menubar>
          <MenubarMenu>
            <MenubarTrigger>Cryptocurrencies</MenubarTrigger>
            <MenubarContent>
              <MenubarItem>
                <Link href="/">Ranking</Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="trending">Trending</Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="gain-loser">Gainers & Losers</Link>
              </MenubarItem>
            </MenubarContent>
          </MenubarMenu>

          <MenubarMenu>
            <MenubarTrigger>Portofolio</MenubarTrigger>
            <MenubarContent>
              <MenubarItem>
                <Link href="portofolio">View My Portofolio</Link>
              </MenubarItem>
            </MenubarContent>
          </MenubarMenu>
        </Menubar>

        <div className="px-4 md:px-0 md:container mx-auto">{children}</div>
      </body>
    </html>
  );
}
